[package]
name = "crawler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scraper = "0.13"
anyhow = "1.0.62"
reqwest = "0.11.11"
futures = "0.3.23"
async-recursion = "1.0.0"
